name: Deploy de la pagina
on:
  push:
    branches:
      - main
jobs:
  deploy-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
<<<<<<< Updated upstream
       uses: actions/checkout@v2.3.1
=======
      uses: actions/checkout@v2.3.1
>>>>>>> Stashed changes

      -name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: . #The folder the action should deploy.
